basic/controllers/RestaurantController.php
<?php

namespace app\controllers;

use app\components\MyHelper;
use app\models\RestaurantComments;
use app\models\RestaurantGrades;
use app\models\User;
use MongoDB\BSON\UTCDateTime;
use Yii;
use app\models\Restaurant;
use app\models\RestaurantSearch;
use app\models\RestaurantSearch2;
use yii\filters\AccessControl;
use yii\helpers\Json;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * RestaurantController implements the CRUD actions for Restaurant model.
 */
class RestaurantController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                //'only' => ['login', 'logout', 'signup'],
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['index2','create-comment','grades-stat1','map',
                                    'comments-stat1','comments-stat2','comment-details2','grade-details2','validate-comment'],
                        'roles' => ['?'],
                    ],
                    [
                        //  'actions' => ['special-callback'],
                        'allow' => true,
                        'matchCallback' => function ($rule, $action) {
                            $u=Yii::$app->getUser();
                            if($u->getIsGuest())

                                return false;
                            elseif( User::isAdmin() === true){
                                return true;
                            }else{//user
                                return in_array($action->id,['index2','index','grades-stat1','map',
                                        'comments-stat1','comments-stat2','embeb-details','comment-details','comment-details2',
                                        'grade-details','grade-details2','validate-comment','validate-grade','update-comment','create-comment'
                                    ]
                                );
                            }
                        }
                    ],

                ],
            ],
        ];
    }

    /**
     * Lists all Restaurant models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new RestaurantSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionGradesStat1(){
        $data = Restaurant::countGradesPerMonth();

        $ajax= Yii::$app->request->get('ajax');
        if (Yii::$app->request->isAjax || $ajax=='true') {
            return $this->renderAjax('grades-stat1', [
                'data' => $data,
            ]);
        }else {
            return $this->render('grades-stat1', [
                'data' => $data,
            ]);
        }
    }

    public function actionCommentsStat1(){
        $data = Restaurant::countCommentsPerDay();

        $ajax= Yii::$app->request->get('ajax');
        if (Yii::$app->request->isAjax || $ajax=='true') {
            return $this->renderAjax('comments-stat1', [
                'data' => $data,
            ]);
        }else {
            return $this->render('comments-stat1', [
                'data' => $data,
            ]);
        }
    }

    public function actionCommentsStat2()
    {
        $data = Restaurant::timeBetweenComments();

        $ajax = Yii::$app->request->get('ajax');
        if (Yii::$app->request->isAjax || $ajax == 'true') {
            return $this->renderAjax('comments-stat2', [
                'data' => $data,
            ]);
        } else {
            return $this->render('comments-stat2', [
                'data' => $data,
            ]);
        }
    }

    /**
     * Lists all Restaurant models.
     * @return mixed
     */
    public function actionIndex2()
    {
        $searchModel = new RestaurantSearch2();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        $b = $this->view->registerAssetBundle(\dosamigos\google\maps\MapAsset::className() );
        $b->options=[
            'key' => 'AIzaSyCJcLn_nkGGMnUtvr9S8cISsmz5C3CfXuY',
            'language' => Yii::$app->language,
            'version' => '3.1.18'
        ];
        $b->init();
        return $this->render('index2', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Lists all Restaurant models.
     * @return mixed
     */
    public function actionMap($id)
    {
        $b = $this->view->registerAssetBundle(\dosamigos\google\maps\MapAsset::className() );
        $b->options=[
            'key' => 'AIzaSyCJcLn_nkGGMnUtvr9S8cISsmz5C3CfXuY',
            'language' => Yii::$app->language,
            'version' => '3.1.18'
        ];
        $b->init();

        $ajax= Yii::$app->request->get('ajax');
        if (Yii::$app->request->isAjax || $ajax=='true') {
            return $this->renderAjax('_map', [
                'model' => $this->findModel($id),
            ]);
        }else {
            return $this->render('_map', [
                'model' => $this->findModel($id),
            ]);
        }
    }

    public function actionTest()
    {
        $model = Restaurant::find()->where(['!=','_id',""])->limit(1)->one();
        //$model->refreshFromEmbedded();

        $a=$model->address;
        foreach($a as $k=>$v) {
            echo "<br>{$k}={$v}";
        }

        return;

        $g = $model->grades;
        foreach($g as $i=>$vv) {
            echo "<br>grade idx({$i})";
            foreach($vv as $k=>$v) {
                if($v instanceof UTCDateTime)
                    $v= $v->toDateTime()->format("Y-m-d ");
                echo "<br>    {$k}={$v}";
            }
        }



    }

    /**
     * Displays a single Restaurant model.
     * @param integer $_id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }


    public function actionValidateRestaurant(){
        if(!Yii::$app->request->isAjax) return "";

        $model = new Restaurant();
        $model->load(Yii::$app->request->post());
        $addr=$model->address;
        $addr->load(Yii::$app->request->post());
        $ret= \yii\widgets\ActiveForm::validate($model);
        $ret= Json::encode($ret);
        return $ret;
    }

    /**
     * Creates a new Restaurant model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Restaurant();
        $model->scenario="create";
        $modelAddress = $model->address;

        $ajax= Yii::$app->request->get('ajax');
        if (Yii::$app->request->isAjax || $ajax=='true') {
            if( $model->load(Yii::$app->request->post()) && $modelAddress->load(Yii::$app->request->post()) &&
                $model->validate()
            ) {
                $model->save();
                \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
                return [
                        'result'=>true,
                        'model'=>$model->toArray()
                    ];
            } else {
                return $this->renderAjax('create', [
                    'model' => $model,
                ]);
            }
        }else {
            if( $model->load(Yii::$app->request->post()) && $modelAddress->load(Yii::$app->request->post()) &&
                $model->validate()
            ) {
                $model->save();
                return $this->redirect(['view', 'id' => (string)$model->_id]);
            } else {
                return $this->render('create', [
                    'model' => $model,
                ]);
            }
        }

    }

    /**
     * Updates an existing Restaurant model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $_id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $model->scenario = 'update';

        $post = Yii::$app->request->post();
        $modelAddress = $model->address;
        $ajax= Yii::$app->request->get('ajax');
        if (Yii::$app->request->isAjax || $ajax=='true') {
            if ($model->load($post) && $modelAddress->load($post) &&
                $model->validate()
            ) {
                $model->save();
                \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
                return [
                    'result'=>true,
                    'model'=>$model->toArray()
                ];
            } else {
                return $this->renderAjax('update', [
                    'model' => $model,
                ]);
            }
        }else {
            if ($model->load($post) && $modelAddress->load($post) &&
                $model->validate()
            ) {
                $model->save();
                return $this->redirect(['view', 'id' => (string)$model->_id]);
            } else {
                return $this->render('update', [
                    'model' => $model,
                ]);
            }
        }
    }

    public function actionEmbedDetails(){
        $id = Yii::$app->request->post('expandRowKey');
        if(empty($id))
            $id=Yii::$app->request->get('id');
        $model = $this->findModel($id);

        $model = $this->findModel($id);
        $modelComments=$model->comments;

        $ajax = Yii::$app->request->get('ajax');

basic/views/restaurant/_formGrade.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\datecontrol\DateControl;

/* @var $this yii\web\View */
/* @var $model app\models\RestaurantGrades */
/* @var $form ActiveForm */
/* @var $id string */
/* @var $idx integer */

if(\app\components\MyHelper::isAjax())
    $this->registerAssetBundle( yii\bootstrap\BootstrapAsset::className()  );
?>

<div class="jumbotron restaurant-updateGrade">

    <?php
    $bs_fieldGroup = "col-xs-offset-0 col-xs-12 col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8 col-lg-offset-3 col-lg-6";
    $bs_label      = "text-left col-xs-12 col-sm-12 col-md-3 col-lg-3";// col-lg-12";
    $bs_input      = "text-left col-xs-12 col-sm-12 col-md-9 col-lg-9";// col-lg-12";
    $bs_error      = "text-left col-xs-12 col-sm-12 col-md-offset-3 col-md-9 col-lg-offset-0 col-lg-12";// col-lg-12";

    $bs_submit     = "col-xs-12 col-sm-12 col-md-12 col-lg-12";

    $form = ActiveForm::begin([
        'id'=>$model->formName(),
        'options' => ['class' => 'row'],
        'action'=>\yii\helpers\Url::current(['layout'=>null]),
        'validationUrl'=>\yii\helpers\Url::toRoute(['restaurant/validate-grade','rest_id'=>$id]),
        'enableAjaxValidation' => true,
        'fieldConfig' => [
            'template' => "<div class=\"".$bs_fieldGroup."\">\n{label}\n".
                "<div class=\"".$bs_input."\">{input}</div>\n".
                "<div class=\"".$bs_error."\">{error}</div>\n</div>",
            'labelOptions' => ['class' => $bs_label.' control-label'],
            'options' => ['class' => 'form-group '],
        ],
    ]); ?>
        <?= Html::hiddenInput('id',$id); ?>
        <?= isset($idx) ? Html::hiddenInput('idx',$idx) : '' ?>
        <?= $form->field($model, 'date2')->widget(DateControl::classname(), [
                'displayFormat' => 'php:d-M-Y',
                'type'=>DateControl::FORMAT_DATE,
               // 'i18n'=>Yii::$app->i18n,
        ]); ?>
        <?php
        /*echo $form->field($model, 'grade')
            ->dropDownList(
                \app\models\RestaurantGrades::SCORES,           // Flat array ('id'=>'label')
                ['prompt'=>'']    // options
            ); */
            echo $form->field($model, 'grade2', ['inputOptions' => [
                    'class'=>'kv-fa rating-loading',
                    'data-size'=>"xs"
                    ]
                ]
            );
        ?>

        <?= $form->field($model, 'score') ?>

        <div class="form-group">
            <div class="<?= $bs_fieldGroup?>">
                <div class="<?= $bs_submit?>">
                    <?= Html::submitButton(!isset($idx) ? Yii::t('restaurant', 'Create') : Yii::t('restaurant', 'Update'),
                                        ['class' => !isset($idx) ? 'btn btn-success btn-lg btn-block' : 'btn btn-primary btn-lg btn-block']) ?>
                </div>
            </div>
        </div>
    <?php ActiveForm::end(); ?>

</div><!-- site-updateGrade -->

<?php
$star = Yii::t("restaurant",'stars');
$stars = Yii::t("restaurant",'stars');
$clear = Yii::t('restaurant', 'Clear');
$clearCaption = Yii::t('restaurant', 'Not Rated');
$script = <<<JS
    
    $('.kv-fa').rating({
        defaultCaption: '{rating} {$stars}',
        starCaptions: function (rating) {
            return rating + (rating == 1 ? ' {$star}' : ' {$stars}');
        },  
        hoverEnabled:false,
        clearButtonTitle: '{$clear}',
        clearCaption: '{$clearCaption}',
        step:1,
    });
JS;
$this->registerJs($script);

if(Yii::$app->request->isAjax ) {
    $script = <<<JS

    $('#{$model->formName()}').submit(function(e){
        var isFormAtRootPage=function(form){
            var min=Math.min($(form).attr('action').length,location.href.length);
            return $(form).attr('action').substr(-min)===location.href.substr(-min);
        }
        e.preventDefault();
        
        var form = $(this);
        var data = form.serialize();
        
        if( typeof window.Storage.{$model->formName()}_posting != "undefined" && window.Storage.{$model->formName()}_posting == true) 
            return false;
        window.Storage.{$model->formName()}_posting = true;
        $.post(
            form.attr('action'),
            data
        )
        .done(function (result, textStatus, jqXHR ) {            
            if (typeof result=="object" && result.result==true) {
                form.trigger('reset');
                if(! isFormAtRootPage(form) ){
                    if(typeof $.fn.modal == "function" && form.closest('.modal').length==1)
                        form.closest('.modal').modal('hide');
                                        
                    /* update owner page */
                    var id= form.find('input[name=id]').val();                   
                    $(document).trigger("refreshOwnerPage", {type:"{$model->formName()}", "id":id});                                                           
                }
            } else {                
                $("#message").html(result.message);
            }
        })
        .fail(function ( jqXHR, textStatus, errorThrown ) {
            console.log("server error");
        }).always(function(){
            window.Storage.{$model->formName()}_posting = false;
        });
        return false;
    });

JS;

    $this->registerJs($script);

}
?>

basic/views/restaurant/_map.php
<?php



/* @var $this yii\web\View */
/* @var $model app\models\Restaurant */

$this->title = Yii::t('restaurant', 'Restaurant location Map');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="restaurant-map">
    <?php
    $coord = new \dosamigos\google\maps\LatLng(['lat' => $model->address->coord[1], 'lng' => $model->address->coord[0]]);
    $map = new \dosamigos\google\maps\Map([
        'center' => $coord,
        'zoom' => 14,
    ]);
    $marker = new \dosamigos\google\maps\overlays\Marker([
        'position' => $coord,
        'title' => $model->name,
    ]);
    $map->addOverlay($marker);
    echo $map->display();
    ?>
</div>
<?php
$script= <<<JS
$(window).resize(function(){
    $('div[id*="-map-canvas"]').each(function(idx,elem){
        var w=$(this).parent().width();
        var map=$(this).data("map");
        $(this).css('width',w);
        
        map.setCenter(new google.maps.LatLng({$model->address->coord[1]},{$model->address->coord[0]}));
        google.maps.event.trigger(map, 'resize');
    });
});
$(window).trigger('resize');    
JS;
$this->registerJs($script);


?>

basic/views/restaurant/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\RestaurantSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="restaurant-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, '_id') ?>

    <?= $form->field($model, 'restaurant_id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'cuisine') ?>

    <?= $form->field($model, 'borough') ?>

    <?php // echo $form->field($model, 'address') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('restaurant', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('restaurant', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

basic/views/restaurant/_view-address.php
<?php

use app\components\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Restaurant */

echo DetailView::widget([
        'model' => $model->address,
        'options' => [
            'data-key'=>$model->id,
        ],
        'attributes' => [
            'building',
            'street',
            'zipcode',
            'coord2',
        ],
    ])
?>

basic/views/restaurant/_view-rest-item.php
<?php

use app\components\DetailView;
use \yii\helpers\Html;
use \yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
/* @var $model app\models\Restaurant */


$mainTag = ['class'=>'rest-item col-xs-12 col-sm-12 col-md-12','data-key'=>$model->getId()];
$minItem = ['class'=>'min-item', ];//'style'=>'padding-bottom:20px'];
$fullInfo = ['class'=>'rest-full-info collapse'];
$mapsInfo = ['class'=>'rest-maps-info collapse'];
$commentsInfo = ['class'=>'rest-item-comments collapse'];
$gradesInfo = ['class'=>'rest-item-grades collapse'];

echo Html::beginTag('div',$mainTag);
    echo Html::beginTag('div',$minItem);
        echo Html::tag('span',$model->name);
        echo Html::tag('button','<span class="glyphicon glyphicon-comment"></span>',[
            //'style'=>'float:right',
            'href'=>'#',
            'class'=>'btn btn-info',
            'data-toggle'=>'collapse',
            'title'=>Yii::t('restaurant','Show comments'),
            'data-target'=>'.rest-item[data-key="'.$model->getId().'"] .rest-item-comments'
        ]);
        echo Html::tag('button','<span class="glyphicon glyphicon-grain"></span>',[
            //'style'=>'float:right',
            'href'=>'#',
            'class'=>'btn btn-info',
            'data-toggle'=>'collapse',
            'title'=>Yii::t('restaurant','Show grades'),
            'data-target'=>'.rest-item[data-key="'.$model->getId().'"] .rest-item-grades'
        ]);
        echo Html::tag('button','<span class="glyphicon glyphicon glyphicon-map-marker"></span>',[
            //'style'=>'float:right',
            'href'=>'#',
            'class'=>'load-modal btn btn-info',
            'data-url'=>\yii\helpers\Url::toRoute(['/restaurant/map','id'=>$model->getId()],true),
            'data-title'=>Yii::t('restaurant','Location Map of restaurant "{name}"',['name'=>$model->name]),
           // 'data-target'=>'.rest-item[data-key="'.$model->getId().'"] .rest-maps-info'
        ]);
        echo Html::tag('button','<span class="glyphicon glyphicon-info-sign"></span>',[
            //'style'=>'float:right',
            'href'=>'#',
            'class'=>'btn btn-info',
            'data-toggle'=>'collapse',
            'title'=>Yii::t('restaurant','More Information'),
            'data-target'=>'.rest-item[data-key="'.$model->getId().'"] .rest-full-info'
        ]);

    echo Html::endTag('div');

    echo Html::beginTag('div',$fullInfo);
        echo $this->render('_view-restaurant',['model'=>$model]).
             $this->render('_view-address',['model'=>$model]);
    echo Html::endTag('div');

    echo Html::beginTag('div',$commentsInfo);
        echo $this->render('commentDetails2',['model'=>$model,'comments'=>$model->comments,'id'=>$model->getId()]);
    echo Html::endTag('div');
    echo Html::beginTag('div',$gradesInfo);
        echo $this->render('gradeDetails2',['model'=>$model,'grades'=>$model->grades,'id'=>$model->getId()]);
    echo Html::endTag('div');
echo Html::endTag('div');

?>

basic/views/restaurant/_view-restaurant.php
<?php

use app\components\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Restaurant */

echo DetailView::widget([
        'model' => $model,
        'options' => [
            'data-key'=>$model->id,
        ],
        'attributes' => [
            'restaurant_id',
            'name',
            'cuisine',
            'borough',
        ],
    ])
?>

basic/views/restaurant/commentDetails.php
<?php

use app\components\DetailView;
use yii\bootstrap\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Restaurant */
/* @var $comments app\models\RestaurantComment */
/* @var $id string */

if(\app\components\MyHelper::isAjax())
    $this->registerAssetBundle( yii\bootstrap\BootstrapAsset::className()  );

?>


<?= Html::button('+',[
        'class'=>'load-modal btn btn-success circular',
        "data-url"  => \yii\helpers\Url::toRoute(['restaurant/create-comment','rest_id'=>$id], true),
        "data-title"=> Yii::t('restaurant','Create Comment about restaurant {name}',['name'=>$model->name]),
    ]);
?>
<div class="rest-comments">

    <?php
    foreach($comments as $idx=> $g):
        echo Html::beginTag('div', [
            'id'        =>"comment" . $idx,
            "class"     => "rest-comment col-xs-12 col-sm-6 col-md-6 col-lg-4",
        ]);
        echo Html::beginTag('div', [
            'class'        =>"load-modal clickable comment-box",
            "data-url"  => \yii\helpers\Url::toRoute(['restaurant/update-comment','rest_id'=>$id,'idx'=>$idx], true),
            "data-title"=> Yii::t('restaurant','Update Comment ({idx}) of {name}',['idx'=>$idx,'name'=>$model->name]),
        ]); ?>
            <h4 ><?= $idx ?></h4>
            <p>
                <?php
                echo DetailView::widget([
                    'model' => $model->comments[$idx],
                    'options' => [
                        'data-key'=>$model->id,
                    ],
                    'attributes' => [
                        'message',
                        [
                            'label' => Yii::t('restaurant','User'),
                            'value' => empty($model->comments[$idx]->user)
                                ? $model->comments[$idx]->name.' - '.$model->comments[$idx]->email
                                : $model->comments[$idx]->user->username.' - '.$model->comments[$idx]->user->email
                            ,
                        ],

                        [
                            'label' => Yii::t('restaurant','Date'),
                            'value' => date('Y-M-d', $model->comments[$idx]->date2),
                        ]
                    ],
                ]);
                ?>
            </p>

    <?php
        echo Html::endTag('div');
        echo Html::endTag('div');
    endforeach;
    ?>
</div>

basic/views/restaurant/commentDetails2.php
<?php

use app\components\DetailView;
use yii\bootstrap\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Restaurant */
/* @var $comments app\models\RestaurantComment */
/* @var $id string */

if(\app\components\MyHelper::isAjax())
    $this->registerAssetBundle( yii\bootstrap\BootstrapAsset::className()  );

?>


<?php
    echo Html::beginTag('div',['class'=>'col-xs-12', ]);
        echo Html::button('+',[
            'class'=>'load-modal btn btn-success circular',
            "data-url"  => \yii\helpers\Url::toRoute(['restaurant/create-comment','rest_id'=>$id], true),
            "data-title"=> Yii::t('restaurant','Create Comment about restaurant {name}',['name'=>$model->name]),
        ]);
        echo Html::tag('span',Yii::t('restaurant','Comments'),['class'=>'comments-title']);
    echo Html::endTag('div');
?>
<div class="rest-comments">

    <?php
    foreach($comments as $idx=> $comment):
        echo Html::beginTag('div', [
            'id'        =>"comment" . $idx,
            "class"     => "rest-comment col-xs-12 col-sm-6 col-md-6 col-lg-4",
        ]);
            echo Html::beginTag('div', [
                'class'        =>"load-modal clickable comment-box",
                "data-url"  => \yii\helpers\Url::toRoute(['restaurant/update-comment','rest_id'=>$id,'idx'=>$idx], true),
                "data-title"=> Yii::t('restaurant','Update Comment ({idx}) of {name}',['idx'=>$idx,'name'=>$model->name]),
            ]);
                echo Html::tag('span',Html::encode($comment->message),['class'=>'comment-message']);
                echo Html::tag('span',Html::encode(date('Y-m-d H:i:s',$comment->date2)),['class'=>'comment-message pull-right']);
            echo Html::endTag('div');
        echo Html::endTag('div');
    endforeach;
    ?>
</div>

basic/views/restaurant/comments-stat1.php
<?php

use yii\helpers\Html;
use miloschuman\highcharts\Highcharts;

/* @var $this yii\web\View */
/* @var $data array */

if(\app\components\MyHelper::isAjax())
    $this->registerAssetBundle( yii\bootstrap\BootstrapAsset::className()  );

$this->title = Yii::t('restaurant', 'Comments Analises');
$this->params['breadcrumbs'][] = ['label' => Yii::t('restaurant', 'Restaurants'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

echo Html::tag('h1',Yii::t('restaurant',''));

$x =array_merge(['x'],$data['year_month']);
echo \app\components\c3\Chart::widget([
    'options' => ['tag' => 'div', 'id'=>'chart_stat2'],
    'clientOptions' => [
        'data'=> [
            'x'=>'x',
            'columns' => [
                $x,
                array_merge(['count'], $data['count']),
                //array_merge(['sum'], $data['sum']),
            ]
        ],
        "axis" => [
            "x" => [

                "type" => 'category',
                "tick" => [
                    "rotate" => 75,
                    "multiline" => false
                ],
                "height" => 130
            ]
        ]
    ]
]);

return;

echo Highcharts::widget([
    'options' => [
        'title' => ['text' => 'Comments Analises'],
        'xAxis' => [
            'categories' => $data['year_month'],
            'title' => ['text' => Yii::t('restaurant','day')],
        ],
        'yAxis' => [
            'title' => ['text' => Yii::t('restaurant','quantity')],
        ],
        'series' => [
            ['name' => Yii::t('restaurant','comments counted'),  'data' => $data['count']],
        ]
    ]
]);

?>

basic/views/restaurant/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Restaurant */

if(\app\components\MyHelper::isAjax())
    $this->registerAssetBundle( yii\bootstrap\BootstrapAsset::className()  );

$this->title = Yii::t('restaurant', 'Create Restaurant');
$this->params['breadcrumbs'][] = ['label' => Yii::t('restaurant', 'Restaurants'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="jumbotron restaurant-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

basic/views/restaurant/createComment.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\datecontrol\DateControl;

/* @var $this yii\web\View */
/* @var $model app\models\RestaurantComments */
/* @var $form ActiveForm */
/* @var $id string */


echo $this->render('_formComment',['model'=>$model,'id'=>$id]);

?>

basic/views/restaurant/createGrade.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\datecontrol\DateControl;

/* @var $this yii\web\View */
/* @var $model app\models\RestaurantGrades */
/* @var $form ActiveForm */
/* @var $id string */


echo $this->render('_formGrade',['model'=>$model,'id'=>$id]);

?>