basic/controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\ES\Restaurant;
use app\models\RestaurantComments;
use app\models\SiteContact;
use MongoDB\BSON\UTCDateTime;
use phpDocumentor\Reflection\DocBlock\Tags\Throws;
use Yii;
use yii\captcha\CaptchaAction;
use yii\data\ActiveDataProvider;
use yii\db\BaseActiveRecord;
use yii\db\Exception;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use yii\helpers\Json;
use yii\helpers\Url;

class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                   // 'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => CaptchaAction::className(),
                //'testLimit'=>-2,
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }


    public function actionMove(){
        $pageSize = 100;
        $page=Yii::$app->request->get('page');
        $page=empty($page)?0:$page;
        $echoModel= function( $model,$i ) use(&$echoModel){
            echo '[';
            foreach ($model as $recno=>$record) {
                echo  '<br>'.str_repeat('&nbsp;',$i*4)  . $recno . ':';

                $isArray=$record instanceof \ArrayObject;
                $felem=$isArray ? reset($record):null;
                $feIsBAR=$felem instanceof  BaseActiveRecord;

                if($isArray && $feIsBAR){
                    foreach ($record as $idx=>$recno)
                        $echoModel( $record,$i+1 );
                }
                else if($record instanceof BaseActiveRecord){
                    $echoModel( $record,$i+1 );
                }else{
                    echo Json::encode($record);
                }
                echo ',';
            }
            echo '}';
            //return $ret;
        };

        do {
            $page++;
            $source = \app\models\Restaurant::find();
            $dataProvider = new ActiveDataProvider([
                'query' => $source,
                'pagination' => [
                    'pageSize' => $pageSize,
                ],
            ]);

            $dataProvider->getPagination()->page=$page;



            $model=null;

            ob_start();
            try {
                echo '<br>{{ ' . $page . ' }}';
                $i=1;
                $models = $dataProvider->getModels();
                foreach ($models as $model) {
                    //echo $echoModel($model,0);

                    $data = $model->getAttributes();
                    unset($data['_id']);

                    $target = new \app\models\ES\Restaurant();


                    echo '<br>('.  (($page - 1) * $pageSize + $i) . ')';
                    if (!($target->load(['Restaurant' => $data]) && $target->validate())) {
                        var_dump($target->getErrors());
                    }else{
                        echo 'restaurant_id:' . $target->restaurant_id;
                        echo '<br>';
                        foreach($target->grades as $ii=>$grade) {
                            if(isset($grade->date)) {
                                $a = $grade->date->toDateTime()->format('Y-m-d\TH:i:s\Z');
                                $grade->date = $a;
                            }
                        }
                        foreach($target->comments as $ii=>$comment) {
                            if(isset($comment->date)) {
                                $a =  $comment->date->toDateTime()->format('Y-m-d\TH:i:s\Z');
                                $comment->date =$a;
                            }
                        }
                        $target->save(false);

                        $i++;
                    }

                }
            }catch (Exception $e) {
                throw $e;
                //echo "<br><br>##### error ##### ". $e->getMessage().', '.$e->getFile().' ( '.$this->$e->getLine()." ) <br>";
            }finally {
                ob_end_flush();
                ob_flush();
                flush();
                unset($source);
                unset($dataProvider);
                unset($target);
            }
        }while(false);
        if(!empty($models)) {
            $url =  Url::to(['site/move', 'page'=>$page], true);
            $js= <<<JS
                <script>
                    document.location.href = "$url";
                </script>         
JS;
        echo $js;
        }else {
            echo "{{ fim }}";
        }

    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }


    public function actionValidateContact(){
        if(!Yii::$app->request->isAjax) return "";

        $model = new SiteContact();

        $model->load(Yii::$app->request->post());
        $ret= \yii\widgets\ActiveForm::validate($model);
        $ret= Json::encode($ret);
        return $ret;
    }
    /**
     * Displays contact page.
     *
     * @return string
     */
    public function actionContact()
    {
        $model = new SiteContact();

        if(! Yii::$app->user->isGuest){
            $u = Yii::$app->user->getIdentity(false);
            $model->name  = $u->username;
            $model->email = $u->email;
        }else
            $model->scenario = SiteContact::SCENARIO_USER_IS_GUEST;

        $ajax= Yii::$app->request->get('ajax');
        if (Yii::$app->request->isAjax || $ajax=='true') {
            if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->contact(Yii::$app->params['adminEmail'])) {
                $model->save(false);
                \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
                return [
                    'result'=>true,
                    'model'=>$model->toArray()
                ];
            }
            return $this->renderAjax('contact', [
                'model' => $model,
            ]);
        }else {
            if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->contact(Yii::$app->params['adminEmail'])) {
                $model->save(false);
                Yii::$app->session->setFlash('contactFormSubmitted');
                return $this->refresh();
            }
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
}

basic/controllers/UserController.php
<?php

namespace app\controllers;

use app\components\MyHelper;
use Yii;
use app\models\User;
use app\models\UserSearch;
use yii\captcha\Captcha;
use yii\captcha\CaptchaAction;
use yii\filters\AccessControl;
use yii\helpers\Json;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                //'only' => ['login', 'logout', 'signup'],
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['register','validate-register-user'],
                        'roles' => ['?'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['logout'],
                        'roles' => ['@'],
                    ],
                    [
                      //  'actions' => ['special-callback'],
                        'allow' => true,
                        'matchCallback' => function ($rule, $action) {
                            $u=Yii::$app->getUser();
                            if($u->getIsGuest())
                                return false;
                            else {
                                return User::isAdmin() === true;
                            }
                        }
                    ],

                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single User model.
     * @param integer $_id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }


    public function actionValidateRegisterUser()
    {
        $model = new User();
        $model->load(Yii::$app->request->post());
        $ret= \yii\widgets\ActiveForm::validate($model);
        $ret= Json::encode($ret);
        return $ret;
    }
    /**
     * validate user rules
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionValidateUser()
    {
        $model = new User();

        if(!Yii::$app->request->isAjax) {
            return "";
        }
        $model->load(Yii::$app->request->post());
        $ret= \yii\widgets\ActiveForm::validate($model);
        $ret= Json::encode($ret);
        return $ret;
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new User();
        $model->state =0;

        $ajax = Yii::$app->request->get('ajax');
        if(Yii::$app->request->isAjax || $ajax==true){
            if ($model->load(Yii::$app->request->post()) && $model->save()) {
                \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
                return [
                    'result'=>true,
                    'model'=>$model->toArray()
                ];
            } else {
                return $this->renderAjax('create', [
                    'model' => $model,
                ]);
            }
        }else {
            if ($model->load(Yii::$app->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => (string)$model->_id]);
            } else {
                return $this->render('create', [
                    'model' => $model,
                ]);
            }
        }
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionRegister()
    {
        $model = new User();
        $model->scenario = 'register'; // extra set of rules ( or just one )

        $model->state =0;
        $ajax = Yii::$app->request->get('ajax');
        if(Yii::$app->request->isAjax || $ajax==true){
            if ($model->load(Yii::$app->request->post()) && $model->save()) {
                \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
                return [
                    'result'=>true,
                    'model'=>$model->toArray()
                ];
            } else {
                return $this->renderAjax('register', [
                    'model' => $model,
                ]);
            }
        }else {
            if ($model->load(Yii::$app->request->post()) && $model->save()) {
                return $this->redirect(['/site/login']);
            } else {
                return $this->render('register', [
                    'model' => $model,
                ]);
            }
        }
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $_id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $model->state =0;

        $ajax = Yii::$app->request->get('ajax');
        if(Yii::$app->request->isAjax || $ajax==true){
            if ($model->load(Yii::$app->request->post()) && $model->save()) {
                \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
                return [
                    'result'=>true,
                    'model'=>$model->toArray()
                ];
            } else {
                return $this->renderAjax('update', [
                    'model' => $model,
                ]);
            }
        }else {
            if ($model->load(Yii::$app->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => (string)$model->_id]);
            } else {
                return $this->render('update', [
                    'model' => $model,
                ]);
            }
        }
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $_id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $_id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

basic/views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = Yii::t('site','About');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="jumbotron site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::encode(Yii::t('site','This is the About page.')) ?>
    </p>
</div>

basic/views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = Yii::t('site','Contact');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="jumbotron site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            <?= Html::encode(Yii::t('site','Thank you for contacting us. We will respond to you as soon as possible.')) ?>
        </div>

    <?php else: ?>

        <p>
            <?= Yii::t('site','If you have business inquiries or other questions, please fill out the following form to contact us. <br> Thank you.') ?>
        </p>
        <?php

            $bs_fieldGroup = "col-xs-offset-0 col-xs-12 col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8 col-lg-offset-2 col-lg-8";
            $bs_label      = "text-left col-xs-12 col-sm-12 col-md-12 col-lg-3";// col-lg-12";
            $bs_input      = "text-left col-xs-12 col-sm-12 col-md-12 col-lg-9";// col-lg-12";
            $bs_error      = "text-left col-xs-12 col-sm-12 col-md-23 col-lg-offset-3 col-lg-9";// col-lg-12";

            $bs_submit     = "col-xs-12 col-sm-12 col-md-12";// col-lg-12";

            $form = ActiveForm::begin([
                'id' => $model->formName(),
                'validationUrl'=>\yii\helpers\Url::toRoute(['site/validate-contact']),
                'enableAjaxValidation' => true,
                'fieldConfig' => [
                    'template' => "<div class=\"".$bs_fieldGroup."\">\n{label}\n".
                        "<div class=\"".$bs_input."\">{input}</div>\n".
                        "<div class=\"".$bs_error."\">{error}</div>\n</div>",
                    'labelOptions' => ['class' => $bs_label.' control-label'],
                    'options' => ['class' => 'form-group row'],
                ]
            ]); ?>
            <?php if(Yii::$app->user->isGuest): ?>
            <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

            <?= $form->field($model, 'email') ?>
            <?php else: ?>
            <?= Html::hiddenInput($model->formName()."[name]",$model->name); ?>
            <?= Html::hiddenInput($model->formName()."[email]",$model->email); ?>
            <?php endif ?>
            <?= $form->field($model, 'subject') ?>

            <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

            <?php if(Yii::$app->user->isGuest): ?>
            <?= $form->field($model, 'verify_code')->widget(Captcha::className(), [
               // 'template' => '<div class="row"><div class="col-lg-5">{image}</div><div class="col-lg-7">{input}</div></div>',
            ]) ?>
            <?php endif ?>
            <div class="form-group row">
                <div class="<?= $bs_fieldGroup?>">
                    <div class="<?= $bs_submit?>">
                        <?= Html::submitButton(Yii::t('site','Submit'),
                            ['class' => 'btn btn-primary btn-lg btn-block', 'name' => 'contact-button']) ?>
                    </div>
                </div>
            </div>

        <?php ActiveForm::end(); ?>

    <?php endif; ?>
</div>

<?php
if(Yii::$app->request->isAjax || \app\components\MyHelper::isAjax()) {
    $script = <<<JS
    $('#{$model->formName()}').submit(function(e){
        var isFormAtRootPage=function(form){
            var min=Math.min($(form).attr('action').length,location.href.length);
            return $(form).attr('action').substr(-min)===location.href.substr(-min);
        }
        e.preventDefault();
        
        var form = $(this);
        var data = form.serialize();
        
        if( typeof window.Storage.{$model->formName()}_posting != "undefined" && window.Storage.{$model->formName()}_posting == true) 
            return false;
        window.Storage.{$model->formName()}_posting = true;
        $.post(
            form.attr('action'),
            data
        )
        .done(function (result, textStatus, jqXHR ) {
            console.log("typeof result="+ typeof result);
            if (typeof result=="object" && result.result==true) {
                form.trigger('reset');
                if(! isFormAtRootPage(form) ){
                    if(typeof $.fn.modal == "function" && form.closest('.modal').length==1)
                        form.closest('.modal').modal('hide');
                                        
                    /* update owner page */
                    $(document).trigger("refreshOwnerPage", {type:"{$model->formName()}", "id":"{$model->getId()}" });
                }
            } else if(typeof result=="object" ){                
                $("#message").html(result.message);
            } else if(isFormAtRootPage(form) ){
                $("body").html(result);           
            }
        })
        .fail(function ( jqXHR, textStatus, errorThrown ) {
            console.log("server error");
        }).always(function(){
            window.Storage.{$model->formName()}_posting = false;
        });
        
        
        return false;
    });

JS;
    $this->registerJs($script);
}
?>

basic/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        <?= Html::encode(Yii::t('app','The above error occurred while the Web server was processing your request.')) ?>
    </p>
    <p>
        <?= Html::encode(Yii::t('app','Please contact us if you think this is a server error. Thank you.')) ?>
    </p>

</div>

basic/views/site/index.php
<?php

/* @var $this yii\web\View */

$this->title = \yii\helpers\Html::encode(Yii::t('app','Challenge8'));
?>
<div class="site-index">

    <div class="jumbotron">
        <h1>Congratulations!</h1>

        <p class="lead">You have successfully created your Yii-powered application.</p>

        <p><a class="btn btn-lg btn-success" href="http://www.yiiframework.com">Get started with Yii</a></p>
    </div>

    <div class="body-content">

        <div class="row">
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/doc/">Yii Documentation &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/forum/">Yii Forum &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/extensions/">Yii Extensions &raquo;</a></p>
            </div>
        </div>

    </div>
</div>

basic/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = Html::encode(Yii::t('user','Login'));
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="jumbotron site-login ">
    <h1><?= $this->title ?></h1>

    <p><?= Html::encode(Yii::t('user','Please fill out the following fields to login:')) ?></p>


    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "<div class=\"col-xs-offset-2 col-xs-8 col-sm-offset-2 col-sm-8 col-md-offset-3 col-md-6 col-lg-offset-4 col-lg-4\">\n{label}\n".
                          "<div class=\"col-xs-12 col-sm-9 col-md-9 col-lg-9\">{input}</div>\n".
                          "<div class=\"text-left col-xs-12 col-sm-offset-3 col-sm-9 col-md-offset-3 col-md-9 col-lg-offset-3 col-lg-9\">{error}</div>\n</div>",
            'labelOptions' => ['class' => 'col-xs-12 text-left-xs col-sm-3 col-md-3 col-lg-3 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox() ?>

        <div class="form-group">
            <div class="col-md-offset-3 col-md-6 col-lg-offset-4 col-lg-4">
                <?= Html::submitButton(Html::encode(Yii::t('user','Login')), ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                <?= Html::a(Html::encode(Yii::t('user','Register')),'/user/register', ['class' => 'btn btn-info', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

</div>