basic/models/User.php
<?php

namespace app\models;

use app\components\models\ActiveRecord;
use app\components\MyHelper;
use Yii;
use yii\web\IdentityInterface;

/**
 * This is the model class for collection "users".
 *
 * @property \MongoDB\BSON\ObjectID|string $_id
 * @property mixed $username
 * @property mixed $email
 * @property mixed $password
 * @property mixed $authKey
 * @property mixed $accessToken
 * @property mixed $state
 * @property mixed $isAdmin
 */
class User extends ActiveRecord implements \yii\web\IdentityInterface
{
    const USER_PENDIND_EMAIL_CONFIRMATION = 0;
    const USER_REGISTERED = 1;
    const USER_DEACTIVATED = 2;

    public $verify_code='';

    public function beforeSave($insert)
    {
        if($this->password !== $this->getOldAttribute('password'))
            $this->password = md5($this->password);
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    static public function getUserStates($state=null){
        $states = [
          0 => Yii::t('user',"Pending email confirmation"),
          1 => Yii::t('user',"Registered"),
          2 => Yii::t('user',"Deactivated"),
        ];
        return is_null($state) ? $states : $states[$state];
    }


    /**
     * @inheritdoc
     */
    public static function collectionName()
    {
        return ['challenge8', 'users'];
    }

    /**
     * @inheritdoc
     */
    public function attributes()
    {
        return [
            '_id',
            'email',
            'username',
            'password',
            'authKey',
            'accessToken',
            'state',
            'isAdmin'
        ];
    }



    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['email','username', 'password', 'authKey', 'accessToken', 'state'], 'safe'],
          //  [['isAdmin'],'unsafe'],
            [['username', 'email', 'password'], 'required'],
            [['email'], 'email'],
            [['email'], 'unique', 'on' => ['register','create']],
            ['email'   , 'string', 'length' => [0,100]],
            ['username', 'string', 'length' => [4,80]],
            ['password', 'string', 'length' => [4,80]],
            ['verify_code', 'captcha', 'on' => 'register'],
        ];

    }

    public function scenarios()
    {
        return [
            "default"   => ['email','username','password','authKey','accessToken','state'],
            "register"  => ['email','username','password','authKey','accessToken','state','verify_code'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            '_id' => Yii::t('user', 'ID'),
            'username' => Yii::t('user', 'Name'),
            'email' => Yii::t('user', 'Email'),
            'password' => Yii::t('user', 'Password'),
            'authKey' => Yii::t('user', 'Auth Key'),
            'accessToken' => Yii::t('user', 'Access Token'),
            'state' => Yii::t('user', 'State'),
            'isAdmin' => Yii::t('user', 'Is Admin'),
            'verify_code' => Yii::t('site', 'Verification Code'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->authKey === $authKey && isset($this->state) && $this->state=self::USER_REGISTERED;
    }

    /**
     * @param string $id MongoId string (not object)
     * @return null|static
     */
    public static function findIdentity($id)
    {
        $id= MyHelper::fix_id($id);
        $user= User::findOne(['_id'=>$id]);
        return isset($user) ? $user : null;
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        $user= User::findOne(['accessToken'=>$token]);
        return isset($user) ? $user : null;
    }

    /**
     * @return \MongoDB\BSON\ObjectID|string
     */
    public function getId()
    {
        return MyHelper::fix_id($this->_id);
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->authKey;
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByEmail($email)
    {
        $user= User::findOne(['email'=>$email]);
        return isset($user)  ? $user : null;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return bool if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return $this->password === md5($password);
    }


    static public function isAdmin() {
        $u = Yii::$app->getUser();
        if( $u->getIsGuest() )
            return false;
        else{
            $id = $u->getIdentity(false);
            return isset($id->isAdmin) && $id->isAdmin==true;
        }
    }


}

basic/controllers/UserController.php
<?php

namespace app\controllers;

use app\components\MyHelper;
use Yii;
use app\models\User;
use app\models\UserSearch;
use yii\captcha\Captcha;
use yii\captcha\CaptchaAction;
use yii\filters\AccessControl;
use yii\helpers\Json;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                //'only' => ['login', 'logout', 'signup'],
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['register','validate-register-user'],
                        'roles' => ['?'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['logout'],
                        'roles' => ['@'],
                    ],
                    [
                      //  'actions' => ['special-callback'],
                        'allow' => true,
                        'matchCallback' => function ($rule, $action) {
                            $u=Yii::$app->getUser();
                            if($u->getIsGuest())
                                return false;
                            else {
                                return User::isAdmin() === true;
                            }
                        }
                    ],

                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single User model.
     * @param integer $_id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }


    public function actionValidateRegisterUser()
    {
        $model = new User();
        $model->load(Yii::$app->request->post());
        $ret= \yii\widgets\ActiveForm::validate($model);
        $ret= Json::encode($ret);
        return $ret;
    }
    /**
     * validate user rules
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionValidateUser()
    {
        $model = new User();

        if(!Yii::$app->request->isAjax) {
            return "";
        }
        $model->load(Yii::$app->request->post());
        $ret= \yii\widgets\ActiveForm::validate($model);
        $ret= Json::encode($ret);
        return $ret;
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new User();
        $model->state =0;

        $ajax = Yii::$app->request->get('ajax');
        if(Yii::$app->request->isAjax || $ajax==true){
            if ($model->load(Yii::$app->request->post()) && $model->save()) {
                \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
                return [
                    'result'=>true,
                    'model'=>$model->toArray()
                ];
            } else {
                return $this->renderAjax('create', [
                    'model' => $model,
                ]);
            }
        }else {
            if ($model->load(Yii::$app->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => (string)$model->_id]);
            } else {
                return $this->render('create', [
                    'model' => $model,
                ]);
            }
        }
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionRegister()
    {
        $model = new User();
        $model->scenario = 'register'; // extra set of rules ( or just one )

        $model->state =0;
        $ajax = Yii::$app->request->get('ajax');
        if(Yii::$app->request->isAjax || $ajax==true){
            if ($model->load(Yii::$app->request->post()) && $model->save()) {
                \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
                return [
                    'result'=>true,
                    'model'=>$model->toArray()
                ];
            } else {
                return $this->renderAjax('register', [
                    'model' => $model,
                ]);
            }
        }else {
            if ($model->load(Yii::$app->request->post()) && $model->save()) {
                return $this->redirect(['/site/login']);
            } else {
                return $this->render('register', [
                    'model' => $model,
                ]);
            }
        }
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $_id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $model->state =0;

        $ajax = Yii::$app->request->get('ajax');
        if(Yii::$app->request->isAjax || $ajax==true){
            if ($model->load(Yii::$app->request->post()) && $model->save()) {
                \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
                return [
                    'result'=>true,
                    'model'=>$model->toArray()
                ];
            } else {
                return $this->renderAjax('update', [
                    'model' => $model,
                ]);
            }
        }else {
            if ($model->load(Yii::$app->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => (string)$model->_id]);
            } else {
                return $this->render('update', [
                    'model' => $model,
                ]);
            }
        }
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $_id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $_id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

basic/views/user/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\User */
/* @var $form yii\widgets\ActiveForm */

if(\app\components\MyHelper::isAjax())
    $this->registerAssetBundle( yii\bootstrap\BootstrapAsset::className()  );
?>


    <?php
    $bs_fieldGroup = "col-xs-offset-0 col-xs-12 col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8 col-lg-offset-2 col-lg-8";
    $bs_label      = "text-left col-xs-12 col-sm-12 col-md-12 col-lg-3";// col-lg-12";
    $bs_input      = "text-left col-xs-12 col-sm-12 col-md-12 col-lg-9";// col-lg-12";
    $bs_error      = "text-left col-xs-12 col-sm-12 col-md-23 col-lg-offset-3 col-lg-9";// col-lg-12";

    $bs_submit     = "col-xs-12 col-sm-12 col-md-12";// col-lg-12";

    ?>
    <?php $form = ActiveForm::begin([
        'id' => $model->formName(),
        'enableAjaxValidation' => true,
        'validationUrl' => \yii\helpers\Url::toRoute(['user/validate-user']),
        //'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "<div class=\"".$bs_fieldGroup."\">\n{label}\n".
                "<div class=\"".$bs_input."\">{input}</div>\n".
                "<div class=\"".$bs_error."\">{error}</div>\n</div>",
            'labelOptions' => ['class' => $bs_label.' control-label'],
            'options' => ['class' => 'form-group row'],
        ],

    ]); ?>

    <?= $form->field($model, 'email') ?>

    <?= $form->field($model, 'username') ?>

    <?= $form->field($model, 'password')->passwordInput() ?>

    <?= $form->field($model, 'authKey') ?>

    <?= $form->field($model, 'accessToken') ?>

    <?= $form->field($model, 'state')
        ->dropDownList(
            \app\models\User::getUserStates(),           // Flat array ('id'=>'label')
            ['prompt'=>'']    // options
        );
    //$form->field($model, 'state') ?>

    <div class="form-group row">
        <div class="<?= $bs_fieldGroup?>">
            <div class="<?= $bs_submit?>">
                <?= Html::submitButton($model->isNewRecord ? Yii::t('user', 'Create') : Yii::t('user', 'Update'),
                    ['class' => $model->isNewRecord ? 'btn btn-success btn-lg btn-block' : 'btn btn-primary  btn-lg btn-block']) ?>
            </div>
        </div>
    </div>

    <?php ActiveForm::end(); ?>

<?php
if(Yii::$app->request->isAjax || \app\components\MyHelper::isAjax()) {
    $script = <<<JS
    $('#{$model->formName()}').submit(function(e){
        var isFormAtRootPage=function(form){
            var min=Math.min($(form).attr('action').length,location.href.length);
            return $(form).attr('action').substr(-min)===location.href.substr(-min);
        }
        e.preventDefault();
        
        var form = $(this);
        var data = form.serialize();
        
        if( typeof window.Storage.{$model->formName()}_posting != "undefined" && window.Storage.{$model->formName()}_posting == true) 
            return false;
        window.Storage.{$model->formName()}_posting = true;
        $.post(
            form.attr('action'),
            data
        )
        .done(function (result, textStatus, jqXHR ) {
            console.log("typeof result="+ typeof result);
            if (typeof result=="object" && result.result==true) {
                form.trigger('reset');
                if(! isFormAtRootPage(form) ){
                    if(typeof $.fn.modal == "function" && form.closest('.modal').length==1)
                        form.closest('.modal').modal('hide');
                                        
                    /* update owner page */
                    $(document).trigger("refreshOwnerPage", {type:"{$model->formName()}", "id":"{$model->getId()}" });

                }
            } else if(typeof result=="object" ){                
                $("#message").html(result.message);
            } else  if(isFormAtRootPage(form) ){
                $("body").html(result);
            }
        })
        .fail(function ( jqXHR, textStatus, errorThrown ) {
            console.log("server error");
        }).always(function(){
            window.Storage.{$model->formName()}_posting = false;
        });
        
        
        return false;
    });

JS;
    $this->registerJs($script);
}
?>

basic/views/user/_formRegister.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\User */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-form">
    <?php
    $bs_fieldGroup = "col-xs-offset-0 col-xs-12 col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8 col-lg-offset-2 col-lg-8";
    $bs_label      = "text-left col-xs-12 col-sm-12 col-md-12 col-lg-3";// col-lg-12";
    $bs_input      = "text-left col-xs-12 col-sm-12 col-md-12 col-lg-9";// col-lg-12";
    $bs_error      = "text-left col-xs-12 col-sm-12 col-md-23 col-lg-offset-3 col-lg-9";// col-lg-12";

    $bs_submit     = "col-xs-12 col-sm-12 col-md-12";// col-lg-12";
    ?>
    <?php $form = ActiveForm::begin([
        'id' => $model->formName(),
        'enableAjaxValidation' => true,
        'validationUrl' => \yii\helpers\Url::toRoute(['user/validate-register-user']),
        'fieldConfig' => [
            'template' => "<div class=\"".$bs_fieldGroup."\">\n{label}\n".
                          "<div class=\"".$bs_input."\">{input}</div>\n".
                          "<div class=\"".$bs_error."\">{error}</div>\n</div>",
            'labelOptions' => ['class' => $bs_label.' control-label'],
            'options' => ['class' => 'form-group row'],
        ],

    ]); ?>

    <?= $form->field($model, 'username') ?>

    <?= $form->field($model, 'email') ?>

    <?= $form->field($model, 'password')->passwordInput() ?>

    <?= $form->field($model, 'verify_code')->widget(\yii\captcha\Captcha::className(), [
      //  'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-9">{input}</div></div>',
    ]) ?>

    <div class="form-group row">
        <div class="<?= $bs_fieldGroup?>">
            <div class="<?= $bs_submit?>">
            <?= Html::submitButton( Yii::t('user', 'Create'),
                                    ['class' => 'btn btn-success btn-lg btn-block']) ?>
            </div>
        </div>
    </div>

    <?php ActiveForm::end(); ?>

</div>

<?php
if(Yii::$app->request->isAjax) {
    $script = <<<JS
    $('#{$model->formName()}').submit(function(e){
        var isFormAtRootPage=function(form){
            var min=Math.min($(form).attr('action').length,location.href.length);
            return $(form).attr('action').substr(-min)===location.href.substr(-min);
        }
        e.preventDefault();
        
        var form = $(this);
        var data = form.serialize();
        
        if( typeof window.Storage.{$model->formName()}_posting != "undefined" && window.Storage.{$model->formName()}_posting == true) 
            return false;
        window.Storage.{$model->formName()}_posting = true;
        $.post(
            form.attr('action'),
            data
        )
        .done(function (result, textStatus, jqXHR ) {
            if (result==true) {
                form.trigger('reset');
                if(! isFormAtRootPage(form) ){
                    if(typeof $.fn.modal == "function" && form.closest('.modal').length==1)
                        form.closest('.modal').modal('hide');
                                        
                    /* update owner page */
                    // $(document).trigger("refreshOwnerPage", {type:"{$model->formName()}", "id":id, "idx":idx });
                    
                    /*
                    other tecnique is update directly on owner page
                    var elem2replace='.kv-expanded-row[data-key="'+id+'"]';
                    console.log(elem2replace);
                  
                    var url = location.origin + location.pathname + '/grade-details?id=' + id;
                    $(elem2replace).load(url );*/
                    /* end update owner form */
                }
            } else {                
                $("#message").html(result.message);
            }
        })
        .fail(function ( jqXHR, textStatus, errorThrown ) {
            console.log("server error");
        }).always(function(){
            window.Storage.{$model->formName()}_posting = false;
        });
        
        return false;
    });

JS;
    $this->registerJs($script);
}
?>

basic/views/user/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\UserSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, '_id') ?>

    <?= $form->field($model, 'email') ?>

    <?= $form->field($model, 'username') ?>

    <?= $form->field($model, 'password') ?>

    <?= $form->field($model, 'authKey') ?>

    <?php // echo $form->field($model, 'accessToken') ?>

    <?php // echo $form->field($model, 'state') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('user', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('user', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

basic/views/user/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\User */

if(\app\components\MyHelper::isAjax())
    $this->registerAssetBundle( yii\bootstrap\BootstrapAsset::className()  );

$this->title = Yii::t('user', 'Create User');
$this->params['breadcrumbs'][] = ['label' => Yii::t('user', 'Users'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="jumbotron user-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

basic/views/user/index.php
<?php

use yii\helpers\Html;
use kartik\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel app\models\UserSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */
use yii\mongodb\Command;
$this->title = Yii::t('user', 'Users');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a(Yii::t('user', 'Create User'), ['create'], ['class' => 'btn btn-success']) ?>
    </p>
<?php Pjax::begin(); ?>    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            [
                'class'=> \app\components\EmailColumn::className(),
                'attribute' => 'email'
            ],
            'username',
            [
                'attribute' => 'state',
                'value'     => function ($model, $key, $index, $column) {
                    if(!isset($model->state))
                        $model->state=0;
                    return \app\models\User::getUserStates($model->state);
                },
            ],

            ['class' => \app\components\ActionColumn::className()],
        ],
    ]); ?>
<?php Pjax::end(); ?></div>

basic/views/user/register.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\User */

if(\app\components\MyHelper::isAjax())
    $this->registerAssetBundle( yii\bootstrap\BootstrapAsset::className()  );

$this->title = Yii::t('user', 'Register User');
$this->params['breadcrumbs'][] = ['label' => Yii::t('user', 'Users'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="jumbotron user-register">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_formRegister', [
        'model' => $model,
    ]) ?>

</div>

basic/views/user/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\User */

if(\app\components\MyHelper::isAjax())
    $this->registerAssetBundle( yii\bootstrap\BootstrapAsset::className()  );

$this->title = Yii::t('user', 'Update {modelClass}', [
    'modelClass' =>  Yii::t('user','User'),
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('user', 'Users'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->email, 'url' => ['view', 'id' => (string)$model->_id]];
$this->params['breadcrumbs'][] = Yii::t('user', 'Update');
?>
<div class="jumbotron user-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

basic/views/user/view.php
<?php

use yii\helpers\Html;
use app\components\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = $model->email;
$this->params['breadcrumbs'][] = ['label' => Yii::t('user', 'Users'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('user', 'Update'), ['update', 'id' => (string)$model->_id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('user', 'Delete'), ['delete', 'id' => (string)$model->_id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('user', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            '_id',
            'email',
            'username',
            [
                'attribute' => 'authKey',
                'format'=>'raw',
                'value'=> isset($model->authKey) ? $model->authKey : ""
            ],
            [
                'attribute' => 'accessToken',
                'format'=>'raw',
                'value'=> isset($model->accessToken) ? $model->accessToken : ""
            ],
            [
                'attribute' => 'state',
                'format'=>'raw',
                'value'=> \app\models\User::getUserStates(isset($model->state) ? $model->state:0)
            ],

        ],
    ]) ?>

</div>